version: "3.8"

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    restart: always
    command: gunicorn --config gunicorn_config.py wsgi:app
    #command: python3 build wsgi.py
    ports:
      - 5000:5000
    volumes:
      - ./services/web:/usr/src/app/
    healthcheck:
            test: ["CMD", "curl", "127.0.0.1:5000"]
            interval: 30s
            timeout: 10s
            retries: 3
  nginx:
    build:
        context: ./services/nginx
        dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/nginx/conf.d:/etc/nginx/conf.d
      - ./data_certbot/certbot/conf:/etc/letsencrypt
      - ./services/nginx/log/nginx:/var/log/nginx/
    healthcheck:
            test: ["CMD", "curl", "127.0.0.1:5000"]
            interval: 30s
            timeout: 10s
            retries: 3

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: sync.aymenrachdi.xyz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./appdata/config:/config
      - ./services/web/content:/config/content
      - ./data1:/data1
      - ./data2:/data2
     
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped


  certbot:
    image: certbot/certbot
    volumes:
      - ./data_certbot/certbot/conf:/etc/letsencrypt
      - ./data_certbot/certbot/www:/var/www/certbot


volumes:
  database:
