

services:
  web:
     build:
       context: ./services/web/quartz
       dockerfile: Dockerfile
     restart: always
     ports:
       - "8080:8080"
     volumes:
       - ./services/web/quartz:/usr/src/app
       - ./services/web/content/blog:/usr/src/app/content
       - /usr/src/app/node_modules
       
     healthcheck:
        test: ["CMD", "curl", "127.0.0.1:5000"]
        interval: 30s
        timeout: 10s
        retries: 3

     command: ["npx", "quartz", "build", "--serve"]
     environment:
       - NODE_ENV=development


  nginx:
    build:
        context: ./services/nginx
        dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/nginx/conf.d:/etc/nginx/conf.d
      - ./data_certbot/certbot/conf:/etc/letsencrypt
      - ./services/nginx/log/nginx:/var/log/nginx/
      - ./services/nginx/webroot:/var/www/certbot
    restart: always
    healthcheck:
            test: ["CMD", "curl", "127.0.0.1:5000"]
            interval: 30s
            timeout: 10s
            retries: 3
            #networks:
            #- compose_frontend

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: sync.aymenrachdi.xyz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./appdata/config:/config
      - ./services/web/content:/config/content
      - ./data1:/data1
      - ./data2:/data2
     
    ports:
      - 8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    #networks:
            #- compose_frontend
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=aymenrachdi.xyz #optional
      - SERVERPORT=51820 #optional
      - PEERS=100 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS=all #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./services/wg/config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=Kernaug_758400 #optional
      - DEFAULT_WORKSPACE=/config/content #optional
    volumes:
      - ./appdata/config:/config
      - ./services/web/content:/config/content
    ports:
      - 8443:8443
    restart: unless-stopped
  mailserver:
    environment:
      # Set SSL certificate type.
      - SSL_TYPE=letsencrypt
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: aymenrachdi.xyz
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/certbot/certs/:/etc/letsencrypt
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
      
  certbot:
        stdin_open: true
        tty: true
        volumes:
            - ${PWD}/docker-data/certbot/certs/:/etc/letsencrypt/
            - ${PWD}/docker-data/certbot/logs/:/var/log/letsencrypt/
            - ./services/nginx/webroot:/var/www/certbot
        image: certbot/certbot
        command: renew --webroot --webroot-path=/var/www/certbot
