"""users table

Revision ID: d6aa72e63695
Revises: ef4a54778379
Create Date: 2022-09-28 15:43:41.179447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6aa72e63695'
down_revision = 'ef4a54778379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=True),
    sa.Column('middleName', sa.String(length=50), nullable=True),
    sa.Column('lastName', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=32), nullable=True),
    sa.Column('registeredAt', sa.DateTime(), nullable=True),
    sa.Column('lastLogin', sa.DateTime(), nullable=True),
    sa.Column('intro', sa.String(length=50), nullable=True),
    sa.Column('PROFILE', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_PROFILE'), 'user', ['PROFILE'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_firstName'), 'user', ['firstName'], unique=True)
    op.create_index(op.f('ix_user_intro'), 'user', ['intro'], unique=True)
    op.create_index(op.f('ix_user_lastLogin'), 'user', ['lastLogin'], unique=False)
    op.create_index(op.f('ix_user_lastName'), 'user', ['lastName'], unique=True)
    op.create_index(op.f('ix_user_middleName'), 'user', ['middleName'], unique=True)
    op.create_index(op.f('ix_user_mobile'), 'user', ['mobile'], unique=True)
    op.create_index(op.f('ix_user_registeredAt'), 'user', ['registeredAt'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorId', sa.String(length=50), nullable=True),
    sa.Column('parentId', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('metaTitle', sa.String(length=50), nullable=True),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('publishedAt', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_authorId'), 'post', ['authorId'], unique=True)
    op.create_index(op.f('ix_post_createdAt'), 'post', ['createdAt'], unique=False)
    op.create_index(op.f('ix_post_metaTitle'), 'post', ['metaTitle'], unique=True)
    op.create_index(op.f('ix_post_parentId'), 'post', ['parentId'], unique=True)
    op.create_index(op.f('ix_post_publishedAt'), 'post', ['publishedAt'], unique=False)
    op.create_index(op.f('ix_post_slug'), 'post', ['slug'], unique=True)
    op.create_index(op.f('ix_post_summary'), 'post', ['summary'], unique=True)
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=True)
    op.create_index(op.f('ix_post_updatedAt'), 'post', ['updatedAt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_updatedAt'), table_name='post')
    op.drop_index(op.f('ix_post_title'), table_name='post')
    op.drop_index(op.f('ix_post_summary'), table_name='post')
    op.drop_index(op.f('ix_post_slug'), table_name='post')
    op.drop_index(op.f('ix_post_publishedAt'), table_name='post')
    op.drop_index(op.f('ix_post_parentId'), table_name='post')
    op.drop_index(op.f('ix_post_metaTitle'), table_name='post')
    op.drop_index(op.f('ix_post_createdAt'), table_name='post')
    op.drop_index(op.f('ix_post_authorId'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_registeredAt'), table_name='user')
    op.drop_index(op.f('ix_user_mobile'), table_name='user')
    op.drop_index(op.f('ix_user_middleName'), table_name='user')
    op.drop_index(op.f('ix_user_lastName'), table_name='user')
    op.drop_index(op.f('ix_user_lastLogin'), table_name='user')
    op.drop_index(op.f('ix_user_intro'), table_name='user')
    op.drop_index(op.f('ix_user_firstName'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_PROFILE'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
